# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/jingling/JingPad_C1/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

LOCAL_SHARED_LIBRARIES := android.hardware.wifi.supplicant@1.0 \
                          android.hardware.wifi.supplicant@1.1 \
                          android.hardware.wifi.supplicant@1.2 \
                          libbase libc++ libcrypto libcutils \
                          libhidlbase libhidltransport libhwbinder \
                          libkeystore-engine-wifi-hidl libkeystore-wifi-hidl \
                          liblog libnl libssl libutils \
                          vendor.sprd.hardware.wifi.supplicant@1.2
